// Generated by Wrangler on Tue Jan 14 2025 18:34:50 GMT+0100 (GMT+01:00)
// by running `wrangler types`

interface Env {
	annonceskv: KVNamespace;
	MY_VARIABLE: "production_value";
	SMTP_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	RECAPTCHA_SECRET_KEY: string;
	DB: D1Database;
}
